# Generated by Django 3.2 on 2021-04-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_from', models.CharField(max_length=10)),
                ('fly_to', models.CharField(max_length=10)),
                ('utc_departure', models.DateTimeField()),
                ('utc_arrival', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('booking_token', models.CharField(max_length=1000)),
                ('last_fetched', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
