# Generated by Django 3.2 on 2021-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='deep_link',
            field=models.URLField(default='www.google.com', max_length=500),
            preserve_default=False,
        ),
    ]
